version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./pet-catalog-service/db_data/:/data/db/

  pet-service:
    build:
      context: pet-catalog-service
    ports:
      - '3000:3000'

  pet-frontend:
    build:
      context: pet-catalog-frontend
    ports:
      - '4000:4000'
